const TAB_ICON_ACTIVE="#000"
const TAB_ICON_INACTIVE="#bbb"
const APP_ORANGE="#ec9902"
const GOLD_MEMBER="#DAA520"
const SILVER_MEMBER="gray"

export  {
    TAB_ICON_ACTIVE,TAB_ICON_INACTIVE,
    APP_ORANGE,GOLD_MEMBER,SILVER_MEMBER
}